package com.cjeg.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.cjeg.mode.AdminUser;
import com.cjeg.mode.User;

public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated
     */
    int insert(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated
     */
    int insertSelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated
     */
    AdminUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminUser record);
    
    AdminUser login(AdminUser user);
    
    /**
     * 根据类型查询所有记录
     * @param record
     * @return
     */
    List<AdminUser> selectBySelective(AdminUser record,RowBounds rowBounds);
    /**
     * 统计个数
     * @param record
     * @return
     */
    long countSelective(AdminUser record);
}