package com.cjeg.mapper;

import java.util.List;

import com.cjeg.mode.Dic;

public interface DicMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dic
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dic
	 * @mbg.generated
	 */
	int insert(Dic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dic
	 * @mbg.generated
	 */
	int insertSelective(Dic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dic
	 * @mbg.generated
	 */
	Dic selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dic
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Dic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dic
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Dic record);

	/**
     * 根据名称查询
     * @param name
     * @return
     */
    List<Dic>selectByName(String name);
}