package com.cjeg.mapper;

import java.util.List;

import org.apache.ibatis.session.RowBounds;

import com.cjeg.mode.Type;

public interface TypeMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int insert(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int insertSelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	Type selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Type record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table type_t
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Type record);

	/**
     * 根据条件查询
     * @param record
     * @param rowBounds
     * @return
     */
    List<Type> selectBySelective(Type record,RowBounds rowBounds);
    
    long countBySelective(Type record);
}