package com.cjeg.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.cjeg.mode.UserBook;

public interface UserBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_book
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_book
     *
     * @mbg.generated
     */
    int insert(UserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_book
     *
     * @mbg.generated
     */
    int insertSelective(UserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_book
     *
     * @mbg.generated
     */
    UserBook selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_book
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_book
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBook record);
    
    List<UserBook> selectBySelective(UserBook book,RowBounds rowBounds);
    long countSelective(UserBook book);
 
    /**
     * 根据状态查询
     * @param book 状态值
     * @param type 0:小于,1:大于
     * @param rowBounds
     * @return
     */
    List <UserBook> selectByStatus(@Param("userBook")UserBook book, @Param("type") int type,RowBounds rowBounds);
}