package com.cjeg.mode;

public class Dic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dic.id
	 * @mbg.generated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dic.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dic.value
	 * @mbg.generated
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dic.descripts
	 * @mbg.generated
	 */
	private String descripts;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dic.id
	 * @return  the value of dic.id
	 * @mbg.generated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dic.id
	 * @param id  the value for dic.id
	 * @mbg.generated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dic.name
	 * @return  the value of dic.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dic.name
	 * @param name  the value for dic.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dic.value
	 * @return  the value of dic.value
	 * @mbg.generated
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dic.value
	 * @param value  the value for dic.value
	 * @mbg.generated
	 */
	public void setValue(String value) {
		this.value = value == null ? null : value.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dic.descripts
	 * @return  the value of dic.descripts
	 * @mbg.generated
	 */
	public String getDescripts() {
		return descripts;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dic.descripts
	 * @param descripts  the value for dic.descripts
	 * @mbg.generated
	 */
	public void setDescripts(String descripts) {
		this.descripts = descripts == null ? null : descripts.trim();
	}
}